### ISSUE TITLE
Allow to work without Charm back-end

### ISSUE THREAD

**Issue by thbar** [cheerful/charmeur#1]
Just a reminder since I plan to do the work anyway (unless someone does it before me!):
- there are two png's to backport into the repo (or recreate?)
- the post url should be configurable

**Comment by thbar** [comment]
@madrobby are you already working on this, or can I take a stab at it tonight?

**Comment by madrobby** [comment]
Stab at it!

**Comment by thbar** [comment]
Closing this one.
